import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "~/lib/utils";
import { ThemeProvider } from "~/components/theme-selector/theme-provider";
import { ThemeToggle } from "~/components/theme-selector/theme-toggle";
import { Separator } from "~/components/ui/separator";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full flex justify-between items-center p-4">
            <h1>Next.js Ethereum Block Explorer</h1>
            <ThemeToggle />
          </div>
          <Separator />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
